### ISSUE TITLE
cannot install in symfony version 3.3.6

### ISSUE THREAD

**Issue by adityarai** [KnpLabs/KnpTimeBundle#100]
$ composer require knplabs/knp-time-bundle
Using version ^1.7 for knplabs/knp-time-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

  [Symfony\Component\Filesystem\Exception\IOException]
  Failed to remove directory "C:\xampp\htdocs\coi\var\cache\de~\profiler\c0":
   .

cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the symfony-scripts event terminated with an exception

Installation failed, reverting ./composer.json to its original content.

  [RuntimeException]
  An error occurred when executing the ""cache:clear --no-warmup"" command:

    [Symfony\Component\Filesystem\Exception\IOException]

    Failed to remove directory "C:\xampp\htdocs\coi\var\cache\de~\profiler\c0
  ":
     .

  cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet]
  [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interact
  ion] [-e|--env ENV] [--no-debug] [--] <command>

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

**Comment by weaverryan** [comment]
Hmm, it looks like there is some write permissions problem with you cache directory. I don't think there's any issue with this bundle. But when you install it (or any package), Symfony tries to clear cache, which fails due to permissions issues. I'm not sure why you have permissions issue (I'm not great with Windows), so I can't offer much help there :/.

Cheers!
