### ISSUE TITLE
Symfony4 support 

### ISSUE THREAD

**Issue by topwebstudio** [KnpLabs/KnpTimeBundle#104]
composer require knplabs/knp-time-bundle outputs error:

> - knplabs/knp-time-bundle v1.2 requires symfony/framework-bundle >=2.0,<2.4-dev -> satisfiable by symfony/framework-bundle[2.0.x-dev, 2.1.x-dev, 2.2.x-dev, 2.3.x-dev].

Adding support for Syfmony4 would be nice!

Pull requests waiting for merge, maybe addressing this issue?
https://github.com/KnpLabs/KnpTimeBundle/pull/103

**Comment by luishdez** [comment]
@Einenlum @weaverryan Can we merge that? Sorry for the ping… :(

**Comment by weaverryan** [comment]
Yep, sorry for the delay!  :D
