### ISSUE TITLE
Pluralization crashing on Symfony 3.4 with 1.9 release

### ISSUE THREAD

**Issue by Zoopme** [KnpLabs/KnpTimeBundle#112]
Hi,

Release 1.9 is making translator's pluralization crash with Symfony 3.4. It shows both singular and plural `1 year ago|4 years ago` options instead of plural only (in my case `4 years ago`). See screenshot below.

![image](https://user-images.githubusercontent.com/12736190/50524542-988a7280-0ad6-11e9-9199-805661593362.png)

I had to downgrade to version 1.8 to make it work.

**Comment by nibsirahsieu** [comment]
Same issue here

**Comment by lyandr** [comment]
I also have this problem with 4.1.x. Is there any solution or is a configuration problem on my side?

**Comment by jkobus** [comment]
Use version 1.8.0. It works with symfony 4.2 (i'm using it).

**Comment by lyandr** [comment]
@jkobus thanks ;)

**Comment by doctorx32** [comment]
downgrading to 1.8.0 for symfony 3.4 helped for me

**Comment by nicolasmure** [comment]
Fixed by #117 and released in [`v1.9.1`](https://github.com/KnpLabs/KnpTimeBundle/releases/tag/v1.9.1).

Thank you for reporting this issue.
