### ISSUE TITLE
Bug - wrong translation files

### ISSUE THREAD

**Issue by MichaelBrauner** [KnpLabs/KnpTimeBundle#115]
Hello, 

in my translation files there is following mistake: 

```
<trans-unit id="1">
                <source>diff.ago.year</source>
                <target>vor einem Jahr|vor %count% Jahren</target>
</trans-unit>
```

So I get results like this:  vor einer Minute|vor 56 Minuten (one minute ago|56 minutes ago)

This bug is in all translations files and for all translations.

**Comment by zerkms** [comment]
I can confirm, it's broken here for me as well in symfony v3.4

**Comment by jacquelotjeff** [comment]
There is a PR to revert the old method to keep the compatibility with Symfony 3.* here : https://github.com/KnpLabs/KnpTimeBundle/pull/114.

**Comment by fyrye** [comment]
Since the only change to `1.9.0` is with `transChoice`. Others experiencing the issue can set your composer version to `"knplabs/knp-time-bundle": "~1.8.0"` which will revert the change.

**Comment by nicolasmure** [comment]
Hello, can you upgrade to `v1.9.1` ? The BC should be restored.

**Comment by fyrye** [comment]
@nicolasmure  I propose merging #118 instead, to avoid calling `class_exists`, and to ensure the translator service is compatible, since the `TranslatorInterface` itself is depreciated in Symfony 4.2 and not just `transChoice`.
