### ISSUE TITLE
symfony/translation dependency v3.4

### ISSUE THREAD

**Issue by zerkms** [KnpLabs/KnpTimeBundle#130]
I see that `"symfony/translation":          "~3.4` dependency was removed in the https://github.com/KnpLabs/KnpTimeBundle/commit/f3d0151965d0597a24568664e4488a2aa222490e commit.

It looks like it was unintentional given adjacent dependencies still support 3.4 branch of the symfony.

Would it be possible to have it back?

**Comment by weaverryan** [comment]
Hmm. You might be right. If I *did* do that on purpose, I wasn’t very clear in my work *why*.

So, can we have it back? Maybe! Can you make a pull request that re-adds it? We can see if the tests pass.

Cheers!

**Comment by zerkms** [comment]
After further investigations (see my couple of PRs) I have found that you did not initially add 3.4 because some types (eg `Symfony\Contracts\Translation\TranslatorInterface`) only exist in symfony v4+, so it's not backward compatible for free.

So I suggest to close this issue, accept my 2 PRs (they fix and improve testing/usability), and leave dependencies as is.

Thanks! :-)
