### ISSUE TITLE
Unusable with translator component disabled.

### ISSUE THREAD

**Issue by Nathanael-Shermett** [KnpLabs/KnpTimeBundle#135]
I am attempting to make use of the Twig `ago` filter in my project. However, for various reasons that are not relevant here, I have the translator component disabled. As a result, this filter (and the bundle as a whole) does not work.

I understand why this bundle uses the translator component, but that utilization should be a feature, not a prerequisite.

Any chance something will be done to change this?

**Comment by jrushlow** [comment]
There are no plans to remove the `symfony/translation` composer requirement at this time. Thanks!
