### ISSUE TITLE
Translations of output

### ISSUE THREAD

**Issue by sigapherve** [KnpLabs/KnpTimeBundle#140]
Good Day,
How can I translate my 'ago' output in another language than English?

I'm an entry-level user/

Rgds

**Comment by weaverryan** [comment]
Hi! Sorry for the very slow reply. That should happen automatically - all the translations are available from this bundle. What you will need to do in your app is make sure the locale is set to whatever language you want: https://symfony.com/doc/current/translation/locale.html

Cheers!
