### ISSUE TITLE
change locale without effect

### ISSUE THREAD

**Issue by Aenos85** [KnpLabs/KnpTimeBundle#142]
I use the ago function in the mailer twig template. 
Before I change the local in the request to the user language. Unfortunately the translator of the ago function does not notice this and renders it in the original language.

**Comment by alexpozzi** [comment]
Hello,
Can you provide a code example to be able to replicate the issue?

Thanks!

**Comment by jrushlow** [comment]
related to #151 with PR #152

**Comment by weaverryan** [comment]
Pr is merged!
