### ISSUE TITLE
Wrong translation for polish version

### ISSUE THREAD

**Issue by luk4szm** [KnpLabs/KnpTimeBundle#157]
Hi!
Can you correct your translation in Polish version please? Instead of `za dzień`,  use `jutro`.

**Comment by PabloKowalczyk** [comment]
> we need another Polish speaker to verify :)

It's easy to check, "jutro" is "tomorrow" in English - https://dictionary.cambridge.org/pl/dictionary/polish-english/jutro :)

**Comment by barat** [comment]
"za dzień" is strange construction ... direct translation in EN would be "for day", you may think that this sentence is some kind of a deal - it'll cost one day.
**Jutro** is the most appropriate form or if we want to use numbers "Za 1 dzień" should be ok, but not best.

**Comment by kacperjurak** [comment]
Of course "jutro" is correct.

**Comment by marcintabaka** [comment]
I'm also voting for `jutro` version.

**Comment by KerbenII** [comment]
same as above.

`jutro` is correct.

**Comment by mleko** [comment]
Both are correct
`jutro` is a bit more natunal and will be symmetric to `wczoraj` in
`<target>wczoraj|%count% dni temu|%count% dni temu</target>`.

**Comment by luk4szm** [comment]
@weaverryan, as you can see, it's not just my frills. It is our beautiful language :)

**Comment by kgasienica** [comment]
Definately ’jutro’ is just perfect.

**Comment by jrushlow** [comment]
A PR to update the translation is welcome..
