### ISSUE TITLE
feat: add "age" formatter 

### ISSUE THREAD

**Issue by seb-jean** [KnpLabs/KnpTimeBundle#190]
Hello,

Do you think it would be nice to add a feature to get the age?

For example :

```twig
{# with filter: #}
Age: {{ user.birthdate|age }} <!-- Age: 30 years old -->

{# ... or use the equivalent function: #}
Age: {{ age(user.birthdate) }} <!-- Age: 30 years old -->
```

**Comment by Chris53897** [comment]
If the age() function get implemented, i suggest to add an optional paramter for a date.
How old is the user on the given date?

user.birthdate = 2000-10-30
now = 2000-08-02
startdateOfJourney = 2000-11-15

Age: {{ age(user.birthdate) }} 
Age: {{ age(user.birthdate, startdateOfJourney) }}

**Comment by Chris53897** [comment]
@seb-jean Would you be up for an PR?

**Comment by seb-jean** [comment]
Yes, i added #192
