### ISSUE TITLE
Wrong "ago" result

### ISSUE THREAD

**Issue by pfpro** [KnpLabs/KnpTimeBundle#200]
Hello KnpLabs, I am happily using the current version of your bundle.

If I use the ago function today ("09/16/2023") for the date "02/27/1900", the result is: 3 years ago.
Is it possible to display "older" data correctly?

**Comment by weaverryan** [comment]
Odd. Can you find where the bug is in the code and propose a fix?

**Comment by pfpro** [comment]
my bad, found the error in my code... sorry for disturbing the peace.

**Comment by pfpro** [comment]
my bad, found the error in my code... sorry for disturbing the peace.
