### ISSUE TITLE
Support for Symfony 7.1

### ISSUE THREAD

**Issue by HolyMacarony** [KnpLabs/KnpTimeBundle#212]
Hello! I'd like to ask whether this bundle can be used in Symfony 7.1 too? 
Because in the last commit d255fe5e1ae877a63ad1cb6a8b2bd40f8bde256a only 7.0 got explicitly enabled.
Thank you !

**Comment by jrushlow** [comment]
Howdy @HolyMacarony - yes this bundle will work with Symfony `7.1`. I've added CI runner to explicitly test against `7.1` on PHP `8.3`.

In our `composer.json`, the constraints use the caret operator `^7.0` - meaning the bundle should work on _all_ 7.x releases that are greater than `7.0` but less than Symfony `8.x`.   
https://github.com/KnpLabs/KnpTimeBundle/blob/33e59bcf1ab63a740540ddd5b44058b862bdaa5c/composer.json#L24

More info on the caret constraint - https://getcomposer.org/doc/articles/versions.md#caret-version-range-
