### ISSUE TITLE
Allow for removing 'ago' word

### ISSUE THREAD

**Issue by cordoval** [KnpLabs/KnpTimeBundle#22]

**Comment by ryall** [comment]
I agree with @nurikabe, `time_diff` feels like it should return a simple time, without prefixes or postfixes.

**Comment by pilot** [comment]
better to implement twig template for date string format

**Comment by Einenlum** [comment]
@akovalyov, @weaverryan, @NicolasNSSM : any news about this?

**Comment by cordoval** [comment]
is better and much easier to just implement twig custom extension
i am not even using this any longer, it was just so simple
