### ISSUE TITLE
Ability to wrap in <abbr> tag

### ISSUE THREAD

**Issue by tomhv** [KnpLabs/KnpTimeBundle#60]
Hey guys,

Do you think it would be possible to have the ability to wrap the time diff in an `<abbr>` tag?

So, something like

```
We shipped your order {{ order.shippedAt|ago }}.
```

would produce:

``` html
We shipped your order <abbr title="2015-03-04 10:00:00">2 months ago</abbr>
```

Not sure if this would be controlled by config or if there'd be a separate filter (`ago_abbr`).

Let me know what you think.

Cheers,

Tom

**Comment by tomhv** [comment]
For now, I've extended the TimeHelper, but I still wonder if it is worth adding as a config item.

```php
<?php

namespace Acme\Bundle\Templating\Helper;

use Knp\Bundle\TimeBundle\Templating\Helper\TimeHelper as BaseTimeHelper;

class TimeHelper extends BaseTimeHelper
{
    /**
     * {@InheritDoc}
     *
     * @param  mixed $since The datetime for which the diff will be calculated
     * @param  mixed $since The datetime from which the diff will be calculated
     *
     * @return string
     */
    public function diff($from, $to = null)
    {
        $from = $this->getDatetimeObject($from);
        $to = $this->getDatetimeObject($to);

        return sprintf(
            '<abbr title="%s">%s</abbr>',
            $from->format('Y-m-d H:i:s T'),
            $this->formatter->formatDiff($from, $to)
        );
    }
}
```

in parameters.yml:

```yml
parameters:
    # ...
    time.templating.helper.time.class: IMC\ToolboxBundle\Templating\Helper\TimeHelper
```

**Comment by pilot** [comment]
yes you made correct or even you can extend datetimeformatter https://github.com/KnpLabs/KnpTimeBundle/blob/master/DateTimeFormatter.php#L80

as well feel free move out of the core the time template line to make ability manage it from the configuration, like we did it in the KnpMenuBundle
