### ISSUE TITLE
Allow specify precision

### ISSUE THREAD

**Issue by m-radzikowski** [KnpLabs/KnpTimeBundle#69]
It would be great if we could change precision of displayed diff. For example, currently `date("-34 days")|ago` shows `month ago`. But maybe it could be some parameter to `ago` to make this more precise, showing `34 days ago`, without rounding it?

**Comment by klb-rodriguez** [comment]
you can see request https://github.com/KnpLabs/KnpTimeBundle/pull/74

**Comment by Einenlum** [comment]
@m-radzikowski  PR #74 was closed, it will not be implemented.
