### ISSUE TITLE
Is the `time.sr_Latn.xml` filename right or it should be `.xliff`?

### ISSUE THREAD

**Issue by zerkms** [KnpLabs/KnpTimeBundle#72]
Symfony does not have the `xml` translation loader by default, which causes the

    The "xml" translation loader is not registered.

exception.

**Comment by akovalyov** [comment]
You are right, both locale an extension are wrong. Closed via https://github.com/KnpLabs/KnpTimeBundle/commit/a8f1c3bf95d4b6ed02e69073542e9f27ef33b2ba and https://github.com/KnpLabs/KnpTimeBundle/commit/9cd598830a2e925e4fb59774fd6bea60ec418074. Thanks for reporting.
@pilot @cvele  it came from #65. Please, be more accurate.

**Comment by pilot** [comment]
@akovalyov wow miss that this is xml, xliff. @zerkms good caught, thanks

**Comment by zerkms** [comment]
@pilot 

> good caught, thanks

that "good caught" broke my deployment pipeline, so I could not miss it even if it wanted :-D

**Comment by fracsi** [comment]
Same here, i had to revert to 1.5.0 to be able to deploy. Any chance of a quick new release?

**Comment by akovalyov** [comment]
@fracsi thanks for pointing it out. I have created https://github.com/KnpLabs/KnpTimeBundle/releases/tag/1.5.2. Could you try and check it?

**Comment by fracsi** [comment]
@akovalyov 
It is working. Thanks.

**Comment by zerkms** [comment]
I can confirm it works, thanks guys.

**Comment by akovalyov** [comment]
@zerkms @fracsi you are welcome and sorry for that headache. If you have any proposals or met a bug - feel free to open the issue.
