### ISSUE TITLE
New Feature: Translations in catalan

### ISSUE THREAD

**Issue by aleixfargas** [KnpLabs/KnpTimeBundle#90]
I've tried to do a pull request, but I always get permission denied (it's my very first time contributing, so maybe I am doing something wrong), so I open this issue to share with all of you the catalan translations for this bundle:

```
<?xml version="1.0"?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
    <file source-language="ca" datatype="plaintext" original="file.ext">
        <body>
            <trans-unit id="1">
                <source>diff.ago.year</source>
                <target>fa 1 any|fa %count% anys</target>
            </trans-unit>
            <trans-unit id="2">
                <source>diff.ago.month</source>
                <target>fa 1 mes|fa %count% mesos</target>
            </trans-unit>
            <trans-unit id="3">
                <source>diff.ago.day</source>
                <target>fa 1 dia|fa %count% dies</target>
            </trans-unit>
            <trans-unit id="4">
                <source>diff.ago.hour</source>
                <target>fa 1 hora|fa %count% hores</target>
            </trans-unit>
            <trans-unit id="5">
                <source>diff.ago.minute</source>
                <target>fa 1 minut|fa %count% minuts</target>
            </trans-unit>
            <trans-unit id="6">
                <source>diff.ago.second</source>
                <target>fa 1 segon|fa %count% segons</target>
            </trans-unit>
            <trans-unit id="7">
                <source>diff.empty</source>
                <target>ara</target>
            </trans-unit>
            <trans-unit id="8">
                <source>diff.in.second</source>
                <target>d'aquí 1 segon|d'aquí %count% segons</target>
            </trans-unit>
            <trans-unit id="9">
                <source>diff.in.hour</source>
                <target>d'aquí 1 hora|d'aquí %count% hores</target>
            </trans-unit>
            <trans-unit id="10">
                <source>diff.in.minute</source>
                <target>d'aquí 1 minut|d'aquí %count% minuts</target>
            </trans-unit>
            <trans-unit id="11">
                <source>diff.in.day</source>
                <target>d'aquí 1 dia|d'aquí %count% dies</target>
            </trans-unit>
            <trans-unit id="12">
                <source>diff.in.month</source>
                <target>d'aquí 1 mes|d'aquí %count% mesos</target>
            </trans-unit>
            <trans-unit id="13">
                <source>diff.in.year</source>
                <target>d'aquí 1 any|d'aquí %count% anys</target>
            </trans-unit>
        </body>
    </file>
</xliff>
```

**Comment by weaverryan** [comment]
Hey @aleixfargas!

Ah, that is weird! And too bad! I'd love for you to get the credit for the commit, so let's try it one more time, but maybe a slightly different way then you tried first :).

1) On the main page (https://github.com/KnpLabs/KnpTimeBundle) click "Fork" in the upper right and then choose your username to fork it. This should take you to a URL like https://github.com/aleixfargas/KnpTimeBundle 

2) Navigate to the Resources/translations directory (URL might be https://github.com/aleixfargas/KnpTimeBundle/tree/master/Resources/translations) and click "Create new file"

3) Add your new file. At the bottom, I believe you should have a radio button that says "Create a new branch for this commit and start a pull request". Write your commit message and choose this option.

4) This should take you to a pull request screen where you can write a message and send it to us! 

But if you have any more problems, just let me know - I can definitely create the file myself.

Cheers!

**Comment by aleixfargas** [comment]
Hi @weaverryan!

Thanks for the help, I appreciate that!

I did all the steps you told me, I forked, created a new branch, commit the new file and created a pull request. When I did all this steps I tried to assign a reviewer, but nobody appears on the filter.
So I clicked the merge button thinking that this would send it as a pull request to the origin bundle, but nothing happened...

What should I do to make this pull request be available from the main repository?
(The pull request in my fork: https://github.com/aleixfargas/KnpTimeBundle/pull/1)

Cheers!

**Comment by weaverryan** [comment]
Ah, I see what happened! It made the pull request against your fork for some reason... but that's ok - because now you have a branch on your fork that contains the changes (https://github.com/aleixfargas/KnpTimeBundle/tree/aleixfargas-patch-1) so we are close now!

Try this:

A) Go to the main repo: https://github.com/KnpLabs/KnpTimeBundle
B) Click "New Pull Request"
C) In the 2 drop-downs at the top of the next screen, choose your "aleixfargas/KnpTimeBundle" "aleixfargas-patch-1" branch

When you do this, you should suddenly see your changes summarized below. Then click to create the pull request! Let me know if this does it!

Cheers!

**Comment by aleixfargas** [comment]
Done!! Thanks for the help @weaverryan, I really appreciate that.

Before closing this issue, do you know of any tutorial to do all this steps from command line?
I am really interested on start contributing on some projects, and I am really interested in learning more about all this stuff.

Again, thanks for your help!

**Comment by weaverryan** [comment]
Awesome! My pleasure :D.

And yes, I might know a place to learn this :). There may be a better source that I don't know of, but we have a good guide on how to contribute to Symfony's core: http://symfony.com/doc/current/contributing/code/patches.html. And these directions should be applicable to any other library. You can also of course use the GitHub interface like we did this time... but those directions show the command-line ways :).

Cheers!
